{% set name = "datashuttle" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 451831fda5fb728783285649e7fb548e805243c104e8f7880a5187582cb2aa80

build:
  noarch: python
  entry_points:
    - "datashuttle = datashuttle.tui_launcher:main"
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation
  number: 1

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python
    - paramiko
    - pyyaml
    - requests
    - rich
    - fancylog >=0.4.2,!=0.5.*,!=0.6.*
    - simplejson
    - rclone
    - pyperclip
    - textual >=3.4.0,<8
    - show-in-file-manager
    - gitpython
    - typeguard
    - psutil
test:
  source_files:
    - datashuttle/
    - tests/
  imports:
    - datashuttle
  commands:
    - pip list
    - pip check
    # exclude transfer tests which require `pass` installed on the system
    - pytest ./tests
      --ignore=tests/tests_integration/test_rclone_encryption.py
      --ignore=tests/tests_transfers/ssh
      --ignore=tests/tests_transfers/gdrive
      --ignore=tests/tests_transfers/aws
  requires:
    - pip
    - pytest
    - pytest-mock
    - pandas
    - pytest-asyncio
    - validators
    - filelock       
    - python-dotenv   
    - python

about:
  home: https://datashuttle.neuroinformatics.dev/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "A project folder manager for systems neuroscience."

extra:
  recipe-maintainers:
    - JoeZiminski
    - adamltyson
    - niksirbi
