{% set name = "datashuttle" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8db35fa46d187a003a0ac65ae2441b71517e717fb90367be60a09c81dd867ab8

build:
  noarch: python
  entry_points:
    - "datashuttle = datashuttle.tui_launcher:main"
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8.0
    - pip
    - setuptools-scm
  run:
    - python >=3.8.0
    - paramiko
    - pyyaml
    - requests
    - rich
    - fancylog >=0.4.2
    - simplejson
    - rclone
    - pyperclip
    - textual
    - show-in-file-manager
    - gitpython
test:
  source_files:
    - datashuttle/
    - tests/
  imports:
    - datashuttle
  commands:
    - pip list
    - pip check
    - pytest ./tests
  requires:
    - pip
    - pytest
    - pandas
    - pytest-asyncio
    - validators

about:
  home: https://datashuttle.neuroinformatics.dev/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "A project folder manager for systems neuroscience."

extra:
  recipe-maintainers:
    - JoeZiminski
    - adamltyson
    - niksirbi
