{% set name = "datashuttle" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fbca788320eecc47c1a93069187091c56f70a280d55257f0a3744cde7ba67ff5

build:
  noarch: python
  entry_points:
    - "datashuttle = datashuttle.tui_launcher:main"
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - paramiko
    - pyyaml
    - requests
    - rich
    - fancylog >=0.4.2
    - simplejson
    - rclone
    - pyperclip
    - textual ==3.4.0
    - show-in-file-manager
    - gitpython
    - typeguard
    - psutil
test:
  source_files:
    - datashuttle/
    - tests/
  imports:
    - datashuttle
  commands:
    - pip list
    - pip check
    - pytest ./tests
  requires:
    - pip
    - pytest
    - pytest-mock
    - pandas
    - pytest-asyncio
    - validators
    - python {{ python_min }}

about:
  home: https://datashuttle.neuroinformatics.dev/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "A project folder manager for systems neuroscience."

extra:
  recipe-maintainers:
    - JoeZiminski
    - adamltyson
    - niksirbi
