{% set name = "datashuttle" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d5f6ae5d06fadda3bd3e514071b84c1d82baa3eac4a6c30ca8e4836a0b4c974b

build:
  noarch: python
  entry_points:
    - "datashuttle = datashuttle.tui_launcher:main"
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - paramiko
    - pyyaml
    - requests
    - rich
    - fancylog >=0.4.2
    - simplejson
    - rclone
    - pyperclip
    - textual <=1.0.0
    - show-in-file-manager
    - gitpython
    - typeguard
test:
  source_files:
    - datashuttle/
    - tests/
  imports:
    - datashuttle
  commands:
    - pip list
    - pip check
    - pytest ./tests
  requires:
    - pip
    - pytest
    - pytest-mock
    - pandas
    - pytest-asyncio
    - validators
    - python {{ python_min }}

about:
  home: https://datashuttle.neuroinformatics.dev/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "A project folder manager for systems neuroscience."

extra:
  recipe-maintainers:
    - JoeZiminski
    - adamltyson
    - niksirbi
