{% set name = "datashuttle" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 36a10d3fe6847f32edf24ff2c8bc6a313a67785630c965f783b6cfee2dd9b1a2

build:
  noarch: python
  entry_points:
    - "datashuttle = datashuttle.command_line_interface:main"
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8.0
    - pip
  run:
    - python >=3.8.0
    - paramiko
    - pyyaml
    - requests
    - rich
    - fancylog
    - simplejson
    - rclone
    - pyperclip
    - textual
    - show-in-file-manager
test:
  source_files:
    - datashuttle/
    - tests/
  imports:
    - datashuttle
  commands:
    - pip list
    - pip check
    - pytest ./tests
  requires:
    - pip
    - pytest
    - pandas

about:
  home: https://datashuttle.neuroinformatics.dev/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "A project folder manager for systems neuroscience."

extra:
  recipe-maintainers:
    - JoeZiminski
    - adamltyson
    - niksirbi
